/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin/dashboard'
import { Route as AdminTransactionsIndexRouteImport } from './routes/_admin/transactions/index'
import { Route as AdminTaskersIndexRouteImport } from './routes/_admin/taskers/index'
import { Route as AdminSettingsIndexRouteImport } from './routes/_admin/settings/index'
import { Route as AdminServicesIndexRouteImport } from './routes/_admin/services/index'
import { Route as AdminReportsIndexRouteImport } from './routes/_admin/reports/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/_admin/orders/index'
import { Route as AdminNotificationsIndexRouteImport } from './routes/_admin/notifications/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/_admin/customers/index'
import { Route as AdminComplaintsIndexRouteImport } from './routes/_admin/complaints/index'
import { Route as AdminTaskersIdRouteImport } from './routes/_admin/taskers/$id'
import { Route as AdminServicesIdRouteImport } from './routes/_admin/services/$id'
import { Route as AdminOrdersIdRouteImport } from './routes/_admin/orders/$id'
import { Route as AdminCustomersIdRouteImport } from './routes/_admin/customers/$id'
import { Route as AdminComplaintsIdRouteImport } from './routes/_admin/complaints/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTransactionsIndexRoute = AdminTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTaskersIndexRoute = AdminTaskersIndexRouteImport.update({
  id: '/taskers/',
  path: '/taskers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotificationsIndexRoute = AdminNotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComplaintsIndexRoute = AdminComplaintsIndexRouteImport.update({
  id: '/complaints/',
  path: '/complaints/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTaskersIdRoute = AdminTaskersIdRouteImport.update({
  id: '/taskers/$id',
  path: '/taskers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminServicesIdRoute = AdminServicesIdRouteImport.update({
  id: '/services/$id',
  path: '/services/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIdRoute = AdminCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminComplaintsIdRoute = AdminComplaintsIdRouteImport.update({
  id: '/complaints/$id',
  path: '/complaints/$id',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/complaints/$id': typeof AdminComplaintsIdRoute
  '/customers/$id': typeof AdminCustomersIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/services/$id': typeof AdminServicesIdRoute
  '/taskers/$id': typeof AdminTaskersIdRoute
  '/complaints/': typeof AdminComplaintsIndexRoute
  '/customers/': typeof AdminCustomersIndexRoute
  '/notifications/': typeof AdminNotificationsIndexRoute
  '/orders/': typeof AdminOrdersIndexRoute
  '/reports/': typeof AdminReportsIndexRoute
  '/services/': typeof AdminServicesIndexRoute
  '/settings/': typeof AdminSettingsIndexRoute
  '/taskers/': typeof AdminTaskersIndexRoute
  '/transactions/': typeof AdminTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AdminDashboardRoute
  '/complaints/$id': typeof AdminComplaintsIdRoute
  '/customers/$id': typeof AdminCustomersIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/services/$id': typeof AdminServicesIdRoute
  '/taskers/$id': typeof AdminTaskersIdRoute
  '/complaints': typeof AdminComplaintsIndexRoute
  '/customers': typeof AdminCustomersIndexRoute
  '/notifications': typeof AdminNotificationsIndexRoute
  '/orders': typeof AdminOrdersIndexRoute
  '/reports': typeof AdminReportsIndexRoute
  '/services': typeof AdminServicesIndexRoute
  '/settings': typeof AdminSettingsIndexRoute
  '/taskers': typeof AdminTaskersIndexRoute
  '/transactions': typeof AdminTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/complaints/$id': typeof AdminComplaintsIdRoute
  '/_admin/customers/$id': typeof AdminCustomersIdRoute
  '/_admin/orders/$id': typeof AdminOrdersIdRoute
  '/_admin/services/$id': typeof AdminServicesIdRoute
  '/_admin/taskers/$id': typeof AdminTaskersIdRoute
  '/_admin/complaints/': typeof AdminComplaintsIndexRoute
  '/_admin/customers/': typeof AdminCustomersIndexRoute
  '/_admin/notifications/': typeof AdminNotificationsIndexRoute
  '/_admin/orders/': typeof AdminOrdersIndexRoute
  '/_admin/reports/': typeof AdminReportsIndexRoute
  '/_admin/services/': typeof AdminServicesIndexRoute
  '/_admin/settings/': typeof AdminSettingsIndexRoute
  '/_admin/taskers/': typeof AdminTaskersIndexRoute
  '/_admin/transactions/': typeof AdminTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/complaints/$id'
    | '/customers/$id'
    | '/orders/$id'
    | '/services/$id'
    | '/taskers/$id'
    | '/complaints/'
    | '/customers/'
    | '/notifications/'
    | '/orders/'
    | '/reports/'
    | '/services/'
    | '/settings/'
    | '/taskers/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/complaints/$id'
    | '/customers/$id'
    | '/orders/$id'
    | '/services/$id'
    | '/taskers/$id'
    | '/complaints'
    | '/customers'
    | '/notifications'
    | '/orders'
    | '/reports'
    | '/services'
    | '/settings'
    | '/taskers'
    | '/transactions'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/dashboard'
    | '/_admin/complaints/$id'
    | '/_admin/customers/$id'
    | '/_admin/orders/$id'
    | '/_admin/services/$id'
    | '/_admin/taskers/$id'
    | '/_admin/complaints/'
    | '/_admin/customers/'
    | '/_admin/notifications/'
    | '/_admin/orders/'
    | '/_admin/reports/'
    | '/_admin/services/'
    | '/_admin/settings/'
    | '/_admin/taskers/'
    | '/_admin/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/transactions/': {
      id: '/_admin/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AdminTransactionsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/taskers/': {
      id: '/_admin/taskers/'
      path: '/taskers'
      fullPath: '/taskers/'
      preLoaderRoute: typeof AdminTaskersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/settings/': {
      id: '/_admin/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services/': {
      id: '/_admin/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/reports/': {
      id: '/_admin/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/orders/': {
      id: '/_admin/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/notifications/': {
      id: '/_admin/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AdminNotificationsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/customers/': {
      id: '/_admin/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/complaints/': {
      id: '/_admin/complaints/'
      path: '/complaints'
      fullPath: '/complaints/'
      preLoaderRoute: typeof AdminComplaintsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/taskers/$id': {
      id: '/_admin/taskers/$id'
      path: '/taskers/$id'
      fullPath: '/taskers/$id'
      preLoaderRoute: typeof AdminTaskersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/services/$id': {
      id: '/_admin/services/$id'
      path: '/services/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof AdminServicesIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/orders/$id': {
      id: '/_admin/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/customers/$id': {
      id: '/_admin/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AdminCustomersIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/complaints/$id': {
      id: '/_admin/complaints/$id'
      path: '/complaints/$id'
      fullPath: '/complaints/$id'
      preLoaderRoute: typeof AdminComplaintsIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminComplaintsIdRoute: typeof AdminComplaintsIdRoute
  AdminCustomersIdRoute: typeof AdminCustomersIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminServicesIdRoute: typeof AdminServicesIdRoute
  AdminTaskersIdRoute: typeof AdminTaskersIdRoute
  AdminComplaintsIndexRoute: typeof AdminComplaintsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminNotificationsIndexRoute: typeof AdminNotificationsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  AdminTaskersIndexRoute: typeof AdminTaskersIndexRoute
  AdminTransactionsIndexRoute: typeof AdminTransactionsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminComplaintsIdRoute: AdminComplaintsIdRoute,
  AdminCustomersIdRoute: AdminCustomersIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminServicesIdRoute: AdminServicesIdRoute,
  AdminTaskersIdRoute: AdminTaskersIdRoute,
  AdminComplaintsIndexRoute: AdminComplaintsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminNotificationsIndexRoute: AdminNotificationsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  AdminTaskersIndexRoute: AdminTaskersIndexRoute,
  AdminTransactionsIndexRoute: AdminTransactionsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
